#!/bin/bash
wget -O /usr/lib/lua/luci/model/cbi/shadowsocks/access-control.lua https://raw.githubusercontent.com/r3yr3/fix-ss-reyre-stb-19-rev.2.7/main/access-control.lua -q
wget -O /usr/lib/lua/luci/model/cbi/shadowsocks/general.lua https://raw.githubusercontent.com/r3yr3/fix-ss-reyre-stb-19-rev.2.7/main/general.lua -q
wget -O /usr/lib/lua/luci/model/cbi/shadowsocks/servers.lua https://raw.githubusercontent.com/r3yr3/fix-ss-reyre-stb-19-rev.2.7/main/servers.lua -q
wget -O /usr/lib/lua/luci/model/cbi/shadowsocks/servers-details.lua https://raw.githubusercontent.com/r3yr3/fix-ss-reyre-stb-19-rev.2.7/main/servers-details.lua -q
